"""
app/services/llm_service.py
===========================
Enterprise LLM integration service for EcoRecon AI.

Provides structured wrappers around LangChain ChatGroq to interact
with the Groq API securely and deterministically.
"""

import json

from langchain_groq import ChatGroq

from app.core.config import get_settings
from app.core.logger import get_logger
from app.prompts.summary_prompt import get_summary_prompt

logger = get_logger(__name__)


class LLMService:
    """
    Service for executing grounded LLM tasks with strict system prompts.
    """

    def __init__(self):
        self._settings = get_settings()
        
        # Initialize LangChain's ChatGroq wrapper for the Groq API
        # Only initialize if the key is present to avoid immediate exceptions
        if self._settings.groq_api_key:
            api_key = self._settings.groq_api_key
            model = "meta-llama/llama-4-scout-17b-16e-instruct"
            logger.info(f"Using Groq API with ChatGroq and model: {model}")
            
            self._llm = ChatGroq(
                groq_api_key=api_key,
                model_name=model,
                temperature=self._settings.groq_temperature,
                max_tokens=self._settings.groq_max_tokens,
            )
        else:
            self._llm = None

    @property
    def is_configured(self) -> bool:
        """Check if the underlying LLM is configured and ready."""
        return self._llm is not None

    async def generate_compliance_summary(self, reconciliation_context: dict) -> str:
        """
        Generate a concise, action-oriented enterprise compliance narrative
        based STRICTLY on the provided deterministic reconciliation context.

        Args:
            reconciliation_context: Dict generated by ReconciliationResult.to_llm_context()

        Returns:
            A 3-5 sentence narrative string.
        """
        if not self.is_configured:
            logger.warning("GROQ_API_KEY missing, using fallback narrative.")
            return "AI narrative unavailable due to missing LLM configuration."

        try:
            logger.debug("Generating compliance summary via Groq API")
            
            prompt = get_summary_prompt()
            chain = prompt | self._llm
            
            # Serialize context dict to a formatted JSON string for the prompt
            context_str = json.dumps(reconciliation_context, indent=2)
            
            response = await chain.ainvoke({"context": context_str})
            
            narrative = str(response.content).strip()
            return narrative
            
        except Exception as e:
            logger.error(f"LLM narrative generation failed: {e}")
            return "AI narrative generation failed during processing."
